### ISSUE TITLE
ALZ Default Policy Assignments Module resulting in file exceeded 4 MB size

### ISSUE THREAD

**Issue by Anto4595** [Azure/ALZ-Bicep#850]
### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Hello @jtracey93 @oZakari 

As you suggested we need to break the script into chunks. I am not sure how to break it and deploy it.

Can you explain in detail how I can do that ?

Thank You...

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

NA

### Please provide the correlation id associated with your error or bug.

NA

### Can you describe any alternatives that you have taken since this feature does not exist?

NA

### Feature Implementation

```Shell
NA
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @Anto4595, with the release of [v0.19.1](https://github.com/Azure/ALZ-Bicep/releases), which I just published, you should no longer encounter the issue unless you're heavily customizing the module by adding additional policy assignments.

If you still need to break it up, the simplest approach is to divide the existing module into separate deployments based on the management group hierarchy. To do this, duplicate the alzDefaultPolicyAssignments.bicep file and the alzDefaultPolicyAssignments.parameters.all.json, rename each copy according to the hierarchies you want to target for the assignments, and then update references (variables, parameters, module references, etc.) so that each file only deploys to the necessary hierarchies.

For example, I created this image to show you how it could be done. The main objective is to reduce the size of the Bicep file, so feel free to break it up as needed.

![image](https://github.com/user-attachments/assets/ce8b08b9-23cb-4d99-8a3b-d6640b84c26e)

Hopefully this helps, but if you need additional clarification feel free to respond back.

**Comment by Anto4595** [comment]
Hello @oZakari Still facing the same issue on the size issue with same error . Eventhough if you have published a new version can you check and advise..

**Comment by andrewj-t** [comment]
I am also experiencing this issue. In my deployment I have an additional Management Group being deployed alongside Corp and Online (parLandingZoneMgChildren) - not sure if that could be the cause.

 I was able to deploy the same configuration in my lab environment last week without issue

**Comment by oZakari** [comment]
The PR that I linked today and release v0.19.2 should work again.
